const datos =
{
    "fechaBase": "2022-01-01",
    "eventos": [
        {
            "id": 1,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/BestSeller.jpg?alt=media&token=6e0a2a06-3a9e-40a9-9f08-bd9ed06fb5a2",
            "name": "Best Seller",
            "date": "2021-10-06",
            "description": "Get to know the best works of literature and take the one you like the most.",
            "category": "Book Exchange",
            "place": "Lounge D6",
            "capacity": 140000,
            "assistance": 110000,
            "price": 200
        },
        {
            "id": 2,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/FantasyBooks.jpg?alt=media&token=b42b103f-2ff9-4cfc-bf87-6251c6ce09c4",
            "name": "Fantasy Books",
            "date": "2022-3-13",
            "description": "The best literary works of a captivating genre full of mythical characters.",
            "category": "Book Exchange",
            "place": "Lounge D4",
            "capacity": 150000,
            "estimate": 123286,
            "price": 3
        },
        {
            "id": 3,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/JustForYourKitchen.jpg?alt=media&token=4dbd1e92-19c9-476b-8cb5-e1fa3a2b6d46",
            "name": "Just For Your Kitchen",
            "date": "2021-11-09",
            "description": "If you are a gastronomy lover, we invite you to look for the book that best suits your tastes and those of your family.",
            "category": "Book Exchange",
            "place": "Lounge D6",
            "capacity": 130000,
            "assistance": 90000,
            "price": 100
        },
        {
            "id": 4,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/Novels%2CMysteryAndHorror.JPG?alt=media&token=6e52f57a-d6e1-45ce-9866-292dc64ae605",
            "name": "Novels, Mystery And Horror",
            "date": "2021-10-06",
            "description": "Three genres acclaimed by readers.",
            "category": "Book Exchange",
            "place": "Lounge D1",
            "capacity": 14000,
            "assistance": 13000,
            "price": 80
        },
        {
            "id": 5,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/OnlyHarry.jpg?alt=media&token=32359fb0-5d63-402f-9720-94f43152f264",
            "name": "Only Harry",
            "date": "2021-10-06",
            "description": "Immerse yourself in the magical world of Harry Potter and live the most unforgettable adventures.",
            "category": "Book Exchange",
            "place": "Lounge D6",
            "capacity": 140000,
            "assistance": 129000,
            "price": 300
        },
        {
            "id": 6,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/SchoolBookFair.JPG?alt=media&token=22b12fd6-ff89-45ba-ae31-6c52bcdb94a2",
            "name": "School Book Fair",
            "date": "2022-10-15",
            "description": "Bring a book to school that you don't use and donate it to the people who need it most.",
            "category": "Book Exchange",
            "place": "Lounge D1",
            "capacity": 150000,
            "estimate": 123286,
            "price": 1
        },
        {
            "id": 7,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/UniversityExchange.jpeg?alt=media&token=925bdad8-904f-48e1-a28e-69c4fdcf5e80",
            "name": "University Exchange",
            "date": "2022-11-09",
            "description": "We invite you to exchange the university books that you no longer use and take one that you do.",
            "category": "Book Exchange",
            "place": "Lounge D1",
            "capacity": 170000,
            "estimate": 143288,
            "price": 1
        },
        {
            "id": 8,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/Avengers.jpg?alt=media&token=0ac9b7c4-eef7-49c0-a648-10943e78d065",
            "name": "Avengers",
            "date": "2021-3-11",
            "description": "Join the universe's mightiest heroes in an epic battle against evil in Avengers.",
            "category": "Cinema",
            "place": "Lounge D2",
            "capacity": 10000,
            "assistance": 8300,
            "price": 125
        },
        {
            "id": 9,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/ForrestGump.jpg?alt=media&token=27dd079d-30e9-4ba1-98e5-1fb16342cee2",
            "name": "Forrest Gump",
            "date": "2022-10-15",
            "description": "Discover the extraordinary life of Forrest Gump in this unforgettable movie.",
            "category": "Cinema",
            "place": "Lounge D1",
            "capacity": 9000,
            "estimate": 9000,
            "price": 250
        },
        {
            "id": 10,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/FreddyKrueger.JPG?alt=media&token=660cdaf2-cdd8-4c44-a8e8-aa9bc227e646",
            "name": "Freddy Krueger",
            "date": "2021-3-11",
            "description": "Delve into terror with the iconic character of Freddy Krueger in A Nightmare on Elm Street.",
            "category": "Cinema",
            "place": "Lounge D2",
            "capacity": 11000,
            "assistance": 10300,
            "price": 225
        },
        {
            "id": 11,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/PrideAndPrejudice.JPG?alt=media&token=f3b636af-69cf-4c34-8acf-dd661e6f229d",
            "name": "Pride And Prejudice",
            "date": "2022-9-15",
            "description": "Discover the adaptation of one of the most romantic classics of all time.",
            "category": "Cinema",
            "place": "Lounge D1",
            "capacity": 9000,
            "estimate": 9000,
            "price": 250
        },
        {
            "id": 12,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/SpiderMan.jpg?alt=media&token=d2a5ba0d-df87-4fb1-a952-1467b65fcb11",
            "name": "Spider Man",
            "date": "2021-9-15",
            "description": "Explore the life of Peter Parker and his fight against crime as Spider-Man.",
            "category": "Cinema",
            "place": "Lounge D2",
            "capacity": 9000,
            "assistance": 6300,
            "price": 125
        },
        {
            "id": 13,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/Titanic.jpg?alt=media&token=95a32d98-0952-42c6-8a5a-51d020ba2831",
            "name": "Titanic",
            "date": "2021-3-11",
            "description": "Relive one of the most romantic stories in the legendary movie Titanic.",
            "category": "Cinema",
            "place": "Lounge D1",
            "capacity": 11000,
            "assistance": 9300,
            "price": 225
        },
        {
            "id": 14,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/ToyStory.JPG?alt=media&token=f3a7cc0c-388e-4602-b101-07c9e23fca52",
            "name": "Toy Story",
            "date": "2022-3-11",
            "description": "Enjoy the adventures of Woody and Buzz Lightyear, in a story where toys come to the life.",
            "category": "Cinema",
            "place": "Lounge D2",
            "capacity": 10000,
            "estimate": 10000,
            "price": 200
        },
        {
            "id": 15,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/CarnivalInRioDeJaneiro.png?alt=media&token=6032254b-3cca-469f-865a-00da5e36a2ee",
            "name": "Carnival In Rio De Janeiro",
            "date": "2021-06-21",
            "description": "Enjoy the rhythm and colors of the Rio Carnival, an unforgettable party full of joy.",
            "category": "Costume Party",
            "place": "Lounge G",
            "capacity": 220000,
            "assistance": 185000,
            "price": 200
        },
        {
            "id": 16,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/Comic-Con2022.jpeg?alt=media&token=3f801b3c-5630-4591-9e39-0b6c2af74380",
            "name": "Comic-Con 2022",
            "date": "2021-02-12",
            "description": "For comic lovers, all your favorite characters in one place.",
            "category": "Costume Party",
            "place": "Lounge C",
            "capacity": 120000,
            "assistance": 110000,
            "price": 54
        },
        {
            "id": 17,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/Comic-Con2024.jpg?alt=media&token=273d1eba-9e6e-48dc-a2a6-940a29ad930b",
            "name": "Comic-Con 2024",
            "date": "2022-02-12",
            "description": " If you liked the previous event, wait until you see what we have prepared for this year.",
            "category": "Costume Party",
            "place": "Lounge D",
            "capacity": 220000,
            "estimate": 220000,
            "price": 104
        },
        {
            "id": 18,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/EpicParty.JPG?alt=media&token=169f5515-8ccf-4432-81e1-578b0f667ab4",
            "name": "Epic Party",
            "date": "2021-09-23",
            "description": "Transform your reality into an epic adventure at festive period costume parties.",
            "category": "Costume Party",
            "place": "Lounge H",
            "capacity": 2000,
            "assistance": 1856,
            "price": 160
        },
        {
            "id": 19,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/ForTheLittleOnes.jpg?alt=media&token=57ad3221-0604-4ab3-aa30-c2ac1b283a52",
            "name": "For The Little Ones",
            "date": "2021-09-23",
            "description": "Bring your little one with their favorite costume and get incredible surprises.",
            "category": "Costume Party",
            "place": "Lounge G",
            "capacity": 10000,
            "assistance": 9327,
            "price": 2
        },
        {
            "id": 20,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/Halloween2024.jpg?alt=media&token=f91de19d-bd06-4ead-8361-d2446db38056",
            "name": "Halloween 2024",
            "date": "2022-10-31",
            "description": "This year the trick or treating is doubled, we are waiting for you with your most terrifying costumes.",
            "category": "Costume Party",
            "place": "Lounge F",
            "capacity": 20000,
            "estimate": 20000,
            "price": 160
        },
        {
            "id": 21,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/HalloweenNight.jpg?alt=media&token=3f6f37dc-2221-4def-bcde-b6dcf9c5bd0e",
            "name": "Halloween Night",
            "date": "2022-02-12",
            "description": "Come with your scariest costume character to win incredible prizes.",
            "category": "Costume Party",
            "place": "Lounge C",
            "capacity": 12000,
            "estimate": 9000,
            "price": 12
        },
        {
            "id": 22,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/SpringDay.jpg?alt=media&token=c6c9058d-27df-4a95-af32-c3925a63af0a",
            "name": "Spring Day",
            "date": "2022-09-21",
            "description": "Immerse yourself in joy and creativity during the spring festivities.",
            "category": "Costume Party",
            "place": "Lounge H",
            "capacity": 220000,
            "estimate": 220000,
            "price": 104
        },
        {
            "id": 23,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/ArabFestivities.jpg?alt=media&token=a1570e81-8a98-43fa-93b1-1e1939f9b7e2",
            "name": "Arab Festivities",
            "date": "2021-10-12",
            "description": "Explore the rich Arab culinary tradition in a feast of captivating aromas and flavors.",
            "category": "Food Fair",
            "place": "Lounge A",
            "capacity": 45000,
            "assistance": 42756,
            "price": 10
        },
        {
            "id": 24,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/CommunityFestival.jpeg?alt=media&token=eac0160e-32f8-40e1-a546-68331a23a656",
            "name": "Community Festival",
            "date": "2021-12-12",
            "description": "Enjoy your favorite dishes from different countries, in a unique event for the whole family.",
            "category": "Food Fair",
            "place": "Lounge A",
            "capacity": 45000,
            "assistance": 42756,
            "price": 5
        },
        {
            "id": 25,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/DirectFromMiddleEast.jpg?alt=media&token=793a92a5-c055-470a-8ed8-edd9f4a71cb5",
            "name": "Direct From Middle East",
            "date": "2021-10-12",
            "description": "All the communities of the Middle East gathered in a unique event to enjoy exotic flavors.",
            "category": "Food Fair",
            "place": "Lounge B",
            "capacity": 45000,
            "assistance": 43000,
            "price": 70
        },
        {
            "id": 26,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/ItalianStyle.jpg?alt=media&token=ee5dc96f-4f5a-43c9-b421-712da1d675b0",
            "name": "Italian Style",
            "date": "2021-10-12",
            "description": "The best dishes from one of the richest culinary cultures.",
            "category": "Food Fair",
            "place": "Lounge A2",
            "capacity": 55000,
            "assistance": 48000,
            "price": 40
        },
        {
            "id": 27,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/JapaneseStyle.jpg?alt=media&token=a161333c-4070-4d86-9d3f-f1e09d8408e3",
            "name": "Japanese Style",
            "date": "2021-06-15",
            "description": "Enjoy the best exhibitors of Korean cuisine, in a Korean gastronomic event full of delicacies.",
            "category": "Food Fair",
            "place": "Lounge A",
            "capacity": 45000,
            "assistance": 42756,
            "price": 10
        },
        {
            "id": 28,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/KoreanStyle.jpg?alt=media&token=899bdc9c-9ef1-4b92-9f6f-6493572a91ec",
            "name": "Korean Style",
            "date": "2021-08-12",
            "description": "Enjoy the best exhibitors of Korean cuisine, with a variety of recipes and the freshest foods.",
            "category": "Food Fair",
            "place": "Lounge A",
            "capacity": 45000,
            "assistance": 42756,
            "price": 10
        },
        {
            "id": 29,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/Takeaway.jpg?alt=media&token=8550fb84-5aa2-4598-ac54-be793d911da4",
            "name": "Takeaway",
            "date": "2021-10-12",
            "description": "If you are a lover of the best of fast food, this is your event, all the main chains, gathered in one place.",
            "category": "Food Fair",
            "place": "Lounge C",
            "capacity": 45000,
            "assistance": 27000,
            "price": 30
        },
        {
            "id": 30,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/Abstracts.JPG?alt=media&token=5ca17bb3-12b2-4c9c-bd9a-1bbc7ed6686a",
            "name": "Abstracts",
            "date": "2022-11-02",
            "description": "Share with us the best works of artists who represent one of the most fascinating trends.",
            "category": "Museum",
            "place": "Buenos Aires",
            "capacity": 1200,
            "estimate": 1200,
            "price": 1500
        },
        {
            "id": 31,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/AcropilisMuseum.jpg?alt=media&token=5f18ecbc-8d4a-4b88-86dd-7b1fa7d5ca6d",
            "name": "Acropilis Museum",
            "date": "2021-11-02",
            "description": "Explore the grandeur of ancient Greece at the Acropolis Museum, a window into a fascinating past.",
            "category": "Museum",
            "place": "Atenas",
            "capacity": 1600,
            "assistance": 1540,
            "price": 8500
        },
        {
            "id": 32,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/BritishMuseum.jpg?alt=media&token=1e337015-a213-41cd-8585-99b7c0ed82d3",
            "name": "British Museum",
            "date": "2022-09-02",
            "description": "Immerse yourself in the emblematic British Museum, an unforgettable experience.",
            "category": "Museum",
            "place": "Inglaterra",
            "capacity": 1200,
            "estimate": 1140,
            "price": 6500
        },
        {
            "id": 33,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/BuenosAiresMALBA.jpg?alt=media&token=cf84d233-6536-4856-b1ed-fbd2665f2f7a",
            "name": "Buenos Aires MALBA",
            "date": "2022-11-02",
            "description": "Unique works by international and national artists are waiting for you in the new exhibition.",
            "category": "Museum",
            "place": "Buenos Aires",
            "capacity": 800,
            "estimate": 800,
            "price": 700
        },
        {
            "id": 34,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/BuenosAiresMuseumOfModernArt.jpg?alt=media&token=6ab80ed1-a5a1-4307-8c14-a558355da616",
            "name": "Buenos Aires Museum Of Modern Art",
            "date": "2021-11-02",
            "description": "Explore artistic innovation at the Museum of Modern Art of Buenos Aires.",
            "category": "Museum",
            "place": "Buenos Aires",
            "capacity": 600,
            "assistance": 550,
            "price": 500
        },
        {
            "id": 35,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/JurassicPark.jpg?alt=media&token=1e14d8ec-496b-4344-a1a7-8d00253c32d8",
            "name": "Jurassic Park",
            "date": "2021-11-02",
            "description": "We are going to the paleontology museum to take an incredible tour to see the largest dinosaurs.",
            "category": "Museum",
            "place": "Field",
            "capacity": 82000,
            "assistance": 65892,
            "price": 15
        },
        {
            "id": 36,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/ParisMuseum.jpg?alt=media&token=8b8ba540-e997-4fe3-991c-c83ba3af75d6",
            "name": "Paris Museum",
            "date": "2022-11-02",
            "description": "Explore art at the iconic Louvre Museum in Paris.",
            "category": "Museum",
            "place": "Paris",
            "capacity": 8200,
            "estimate": 8200,
            "price": 3500
        },
        {
            "id": 37,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/ElectroFest.jpg?alt=media&token=5b914070-884f-408b-9a92-3fc26dd72238",
            "name": "Electro Fest",
            "date": "2021-01-22",
            "description": "The best national and international DJs in one place.",
            "category": "Music Concert",
            "place": "Lounge A",
            "capacity": 138000,
            "assistance": 110300,
            "price": 250
        },
        {
            "id": 38,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/MetallicaInBuenosAires.jpg?alt=media&token=048b1682-a237-4926-8121-ada859469776",
            "name": "Metallica In Buenos Aires",
            "date": "2021-06-23",
            "description": "The city of Buenos Aires brings us a unique recital with all the greatest hits of the legendary band from the 80s.",
            "category": "Music Concert",
            "place": "Buenos Aires",
            "capacity": 138000,
            "assistance": 137560,
            "price": 1300
        },
        {
            "id": 39,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/MetallicaInConcert.jpg?alt=media&token=b935e03a-e7ac-4a77-8d3c-37b7f71c4b68",
            "name": "Metallica In Concert",
            "date": "2022-01-22",
            "description": "Only recital of the most emblematic band.",
            "category": "Music Concert",
            "place": "Lounge A",
            "capacity": 138000,
            "estimate": 138000,
            "price": 150
        },
        {
            "id": 40,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/PopularMusic.jpeg?alt=media&token=81be3d01-f29a-42e3-92c9-c971f727407b",
            "name": "Popular Music",
            "date": "2021-05-22",
            "description": "Enjoy the best of popular music, brought together in a single event for you to enjoy with your family.",
            "category": "Music Concert",
            "place": "Lounge C",
            "capacity": 238000,
            "assistance": 183300,
            "price": 40
        },
        {
            "id": 41,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/Opera.png?alt=media&token=1c3f72e5-0e15-499f-9a1b-8e05029d851e",
            "name": "Opera",
            "date": "2022-05-22",
            "description": "Embark on an emotional journey through the music and passion of an opera concert.",
            "category": "Music Concert",
            "place": "Lounge F",
            "capacity": 138000,
            "estimate": 138000,
            "price": 1500
        },
        {
            "id": 42,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/Reggaeton2022.jpg?alt=media&token=d12cc11e-78fb-4172-afe3-b845103e877f",
            "name": "Reggaeton 2022",
            "date": "2022-06-23",
            "description": "If you danced in the last editions, you can't miss this one. The best artists of the genre await you.",
            "category": "Music Concert",
            "place": "Lounge G",
            "capacity": 2138000,
            "estimate": 2138000,
            "price": 300
        },
        {
            "id": 43,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/SanFranciscoSymphony.jpg?alt=media&token=c641921f-7075-4e6c-90a7-96f5dcaa1dc5",
            "name": "San Francisco Symphony",
            "date": "2021-06-23",
            "description": "One of the best symphonic bands in the world awaits you in a unique show.",
            "category": "Music Concert",
            "place": "Buenos Aires",
            "capacity": 38000,
            "assistance": 36560,
            "price": 1300
        },
        {
            "id": 44,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/TheClassicsOfAllTime.jpg?alt=media&token=3fa09ecc-1e16-464e-9131-fd25cb549ea7",
            "name": "The Classics Of All Time",
            "date": "2021-05-22",
            "description": "Relive the classics of today and always.",
            "category": "Music Concert",
            "place": "Lounge B",
            "capacity": 38000,
            "assistance": 13300,
            "price": 20
        },
        {
            "id": 45,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/15KForBuenosAires.JPG?alt=media&token=a9a92a35-c663-4700-9e68-452b97ff76d1",
            "name": "15K For Buenos Aires",
            "date": "2021-03-01",
            "description": "Join us in a race through Buenos Aires for a healthier life.",
            "category": "Race",
            "place": "Buenos Aires",
            "capacity": 300000,
            "assistance": 256980,
            "price": 2
        },
        {
            "id": 46,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/10KForLife.jpg?alt=media&token=59f42960-c154-4288-b896-9328f6578dce",
            "name": "10K For Life",
            "date": "2021-03-01",
            "description": "Come and exercise, improve your health and your lifestyle.",
            "category": "Race",
            "place": "Football Field",
            "capacity": 30000,
            "assistance": 25698,
            "price": 3
        },
        {
            "id": 47,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/15KForNewYork.jpg?alt=media&token=7c64684e-97d3-4cce-a19d-de563230ce1e",
            "name": "15K For New York",
            "date": "2021-03-01",
            "description": "Challenge your limits in the vibrant 15K race through the iconic streets of New York.",
            "category": "Race",
            "place": "New York",
            "capacity": 3000000,
            "assistance": 2569800,
            "price": 3
        },
        {
            "id": 48,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/BuenosAires2022.JPG?alt=media&token=9df3e5a8-713a-444a-901d-827f6325dd99",
            "name": "Buenos Aires 2022",
            "date": "2022-03-01",
            "description": "Discover the unique energy of Buenos Aires in an exciting race full of culture.",
            "category": "Race",
            "place": "Buenos Aires",
            "capacity": 300000,
            "estimate": 300000,
            "price": 2
        },
        {
            "id": 49,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/RaceAgainstCancer.jpeg?alt=media&token=ab889d83-1710-4b9b-9d30-6750c189d098",
            "name": "Race Against Cancer",
            "date": "2021-03-01",
            "description": "Transform steps into hope in the solidarity race against cancer, every step counts in the fight",
            "category": "Race",
            "place": "Mar del Plata",
            "capacity": 1800000,
            "assistance": 1800000,
            "price": 1
        },
        {
            "id": 51,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/RaceNewYork2022.jpg?alt=media&token=f34d7d34-ca9b-4bdf-ae46-1de988c77deb",
            "name": "Race New York 2022",
            "date": "2022-03-01",
            "description": "We are waiting for you in the new marathon crossing the skyscrapers of the Big Apple",
            "category": "Race",
            "place": "New York",
            "capacity": 5000000,
            "estimate": 5000000,
            "price": 2
        },
        {
            "id": 50,
            "image": "https://firebasestorage.googleapis.com/v0/b/amazingeventszg.appspot.com/o/WalkForLife2ndEdition.jpg?alt=media&token=c4c8bd3c-fdc3-4b1a-8609-18cf93b92ecf",
            "name": "Walk For Life 2nd Edition",
            "date": "2022-03-01",
            "description": "If you enjoyed the first edition, we are waiting for you for the second edition.",
            "category": "Race",
            "place": "Cordoba",
            "capacity": 200000,
            "estimate": 200000,
            "price": 1
        }
        
    ]
}